### PR TITLE
Replace MariaDB's TRANSACTIONAL=1 create table option when destination is MySQL.

### LINKED ISSUE #16: Add example fix for when MariaDB uses TRANSACTIONAL in create table options
When migrating from MariaDB to MySQL and the Aria engine in MariaDB has the TRANSACTIONAL setting enabled it adds `TRANSACTIONAL=1` to the `CREATE TABLE` options.

We should alter the example for `wpmdb_create_table_query` to show how to fix this.

### PR DESCRIPTION
**Pull request by ianmjones**
Resolves #16

### CODE REVIEW

**Comment by dylandownhill** [comment]
In my environment it also needs the line:
$create_table_query = preg_replace( '/PAGE_CHECKSUM\s?=\s?./', '', $create_table_query );

Added to allow MariaDB to transfer to MySQL cleanly

**Comment by JRGould** [comment]
@ianmjones is this still good to be merged?

**Comment by ianmjones** [comment]
@JRGould Yes please!

**Comment by dylandownhill** [comment]
@JRGould - I see the merge but it's missing the line needed for my environment (the "page_checksum" line) - is it possible to add this line too?

**Pull request merged**
